# Generated by Django 2.2.13 on 2024-05-27 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20201106_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='category_for_the_auction', to='auctions.Category'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='person',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='person_to_use', to='auctions.Person'),
        ),
    ]
